# Generated by Django 4.1.3 on 2023-01-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibo',
            name='money',
            field=models.IntegerField(verbose_name='金額'),
        ),
    ]
