# Generated by Django 4.1.5 on 2023-01-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_kakeibo_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibo',
            name='io_flag',
            field=models.IntegerField(choices=[(1, '入金'), (0, '出金')]),
        ),
    ]
