# Generated by Django 4.1.5 on 2023-01-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_kakeibo_io_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_code', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='タグコード')),
                ('tag_name', models.CharField(blank=True, max_length=30, verbose_name='タグ名称')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterField(
            model_name='kakeibo',
            name='io_flag',
            field=models.IntegerField(choices=[(0, '出金'), (1, '入金')], verbose_name='入払区分'),
        ),
        migrations.AlterField(
            model_name='kakeibo',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes.tag'),
        ),
    ]
