# Generated by Django 4.1.5 on 2023-01-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_tag_alter_kakeibo_io_flag_alter_kakeibo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_code',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='タグコード'),
        ),
    ]
